name: store_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^0.13.6

dev_dependencies:
  flutter_lints: ^2.0.0
  icons_launcher: ^3.0.0 
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
flutter:
  assets:
    - assets/logo.png
  uses-material-design: true
